### ISSUE TITLE
Rocks and metal now comes out of the ground in random locations

### ISSUE THREAD

**Issue by DanAugust** [Uwazouri/top-mining#1]
I have not used this mod for a while, but when mining something like Silver or Copper, the rocks and ore pop out of the ground at random locations around the metal deposit. It is especially an issue when mining silver in the mountains. Ore will pop out of the ground and roll down the mountain most of the time!

**Comment by Uwazouri** [comment]
After testing the fix from Vladislav this seems to have been fixed.
